### ISSUE TITLE
func New(string) (def Definition, err error) is not found

### ISSUE THREAD

**Issue by 80163916** [alecthomas/repr#15]
The func New(ebnf string) (def Definition, err error) is not found in packages of ebnf.go.

**Comment by alecthomas** [comment]
Did you mean this to be in alecthomas/participle instead of here?

**Comment by 80163916** [comment]
I appreciate your response.
 "github.com/alecthomas/participle/ebnf" has not found “func New(string)"
package parser :19     
smiLexer = lexer.Must(ebnf.New('
                 Keyword = "FROM" .
		ObjectIdentifier = "OBJECT" Whitespace { Whitespace } "IDENTIFIER" .
		OctetString = "OCTET" Whitespace { Whitespace } "STRING" .
		BinString = "'" { "0" | "1" } "'" ( "b" | "B" ) .
		HexString = "'" { digit | "a"…"f" | "A"…"F" } "'" ( "h" | "H" ) .
		Assign = "::=" .
		Comment = "--" { "\u0000"…"\U0010ffff"-"\n" } .
		ExtUTCTime = "\"" digit digit digit digit digit digit digit digit digit digit [ digit digit ] ( "z" | "Z" ) "\"" .
		Text = "\"" { "\u0000"…"\U0010ffff"-"\"" } "\"" .
		Ident = alpha { alpha | digit | "-" | "_" } .
		Int = "0" | ( digit { digit } ) .
		Punct = ".." | "!"…"/" | ":"…"@" | "["…` + "\"`\"" + ` | "{"…"~" .
		Whitespace = " " | "\t" | "\n" | "\r" .

		lower = "a"…"z" .
		upper = "A"…"Z" .
		alpha = lower | upper .
		digit = "0"…"9" .
	`))
