### ISSUE TITLE
infinite loop while dumping structures containing pointers

### ISSUE THREAD

**Issue by pnck** [alecthomas/repr#3]
i have a struct like
```go
type data struct {
	parent *data
	children   []*data
}
type dataInterface interface {
	AddChild(data)
	SetParent(parent *data)
}
```
if i want to dump such a structure, i got infinite loop
`repr` is trying to dereference every pointer then it will do d->parent->child->parent->child..on and on..
any ideas to avoid this?

**Comment by alecthomas** [comment]
Better late than never, but this was fixed quite some time ago!
