### ISSUE TITLE
TestReprByteArray fails with latest commit ead2165 dated 2018-07-24

### ISSUE THREAD

**Issue by anthonyfok** [alecthomas/repr#4]
Hi @alecthomas.

TestReprByteArray fails with latest commit ead2165 dated 2018-07-24, as seen on Travis CI:

```
=== RUN   TestReprByteArray
--- FAIL: TestReprByteArray (0.00s)
	repr_test.go:77: 
			Error Trace:	repr_test.go:77
			Error:      	Not equal: 
			            	expected: "[]uint8{1, 2, 3}"
			            	actual  : "[]byte(\"\\x01\\x02\\x03\")"
			            	
			            	Diff:
			            	--- Expected
			            	+++ Actual
			            	@@ -1 +1 @@
			            	-[]uint8{1, 2, 3}
			            	+[]byte("\x01\x02\x03")
			Test:       	TestReprByteArray
```

I encountered this exact same error on my Debian box while I was trying to update the Debian packaging for golang-github-alecthomas-repr.

Thanks in advance for looking into this.

**Comment by alecthomas** [comment]
Sorry about that, and thanks for reporting!

**Comment by anthonyfok** [comment]
> Sorry about that, and thanks for reporting!

No worries, and thanks for such a prompt response and resolution!
